export const GRID_LOCALIZATION_DEFAULTS = new Map<string, string>([
  ["locSetValues", "Set values"],
  ["locCopySelection", "Copy selection"],
  ["locDeleteRecords", "Delete records"],
  ["locClearSelection", "Clear selection"],
  ["locAccessToTheClipboardWasDenied", "Access to the clipboard was denied"],
  ["locPleaseAllowClipboardReadAccessToEnableThePasteOperation", "Please allow clipboard read access to enable the past operation"],
  ["locClose", "Close"],
  ["locCommitAllRecords", "Commit all records"],
  ["locCommitSelectedRecord(s)", "Commit selected record(s)"],
  ["locCopySelectedCell(s)", "Copy selected cell(s)"],
  ["locDeleteRecord(s)", "Delete record(s)"],
  ["locInsertRecord", "Insert record"],
  ["locInsertAtTop", "Insert at top"],
  ["locInsertAboveSelection", "Insert above selection"],
  ["locInsertBelowSelection", "Insert below selection"],
  ["locInsertAtBottom", "Insert at bottom"],
  ["locPaste", "Paste"],
  ["locRevertAllRecords", "Revert all records"],
  ["locRevertSelectedRecord(s)", "Revert selected record(s)"],
  ["locRecordsSelected", "records selected"],
  ["locCheckAll", "Check all"],
  ["locInvertValues", "Invert values"],
  ["locUncheckAll", "Uncheck all"],
  ["locClearValues", "Clear values"],
  ["locAddDays", "Add days"],
  ["locSubtractDays", "Subtract days"],
  ["locAdd", "+ Add"],
  ["locDivide", "÷ Divide"],
  ["locDivideBy", "÷ Divide by"],
  ["locMultiply", "× Multiply"],
  ["locMultiplyBy", "× Multiply by"],
  ["locSubtract", "− Subtract"],
  ["locAppendText", "Append text ↦"],
  ["locPrependText", "↤ Prepend text"],
  ["locInsertARecordAbove", "Insert a record above"],
  ["locInsertARecordBelow", "Insert a record below"],
  ["locCopySelection", "Copy selection"],
  ["locUploadANewFile", "Upload a new file"],
  ["locLinkToARecordFrom", "Link to a record from"],
  ["locSelectAnOption", "Select an option"],
  ["locRemoveFile", "Remove File"],
  ["locDownloadFile", "Download File"],
])
