# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish NGX Grid Core

on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:      
      - name: Download Ngx Grid Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          name: ngx-grid-core
          branch: main
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          #cd ./artifacts
          #npm publish --access public
          ls -la
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
