name: Publish NGX Grid Core

on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:      
      - name: Download Ngx Grid Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          name: ngx-grid-core
          branch: main
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          curVersion=$(jq -r .version ./package.json)
          prevVersion=$(cat previous_package_version)
          if [ "$curVersion" != "$prevVersion" ]; then
            rm previous_package_version
            npm publish --access public
          else
            echo "Versions didn't change. No new version to publish."
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
